package com.project275;


import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.util.List;
import java.util.Set;
import java.util.Vector;

import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import com.project275.controller.TaskTableController;
import com.project275.controller.ProjPlannerController;
import com.project275.entity.Project;
import com.project275.entity.Task;
import com.project275.entity.TeamMember;
import com.project275.entity.User;
import com.project275.service.ProjectService;
import com.project275.service.UserService;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 
 */
public class MainFrame5 extends javax.swing.JFrame {
	private TaskTableController taskTableController;
	private String projectName = "project1";
	private boolean isAdmin = false;;
	private ProjPlannerController projPlannerController; // glue between model and gui
	private int iProjectID=0;
    /**
     * Creates new form MainFrame5
     */
    public MainFrame5(String projectName,boolean isAdmin) {
    	this.projectName = projectName;
    	this.isAdmin = isAdmin;
        initComponents();
        projPlannerController = new ProjPlannerController(this);
        taskTableController = new TaskTableController(this, projectName);
        addTaskEntryTable();
    }

    
    public void addTaskEntryTable() {
		// add the data and column names to a JTable
		//jtable1  = new JTable(courseListTableController.getData(), courseListTableController.getColumnNames());
	   
	    taskEntryTable = new JTable(taskTableController.getTableModel());
		// add a ListSelectionListener to the table
	    taskEntryTable.getSelectionModel().addListSelectionListener(taskTableController);
		
		// add the table to a scrollpane
		JScrollPane scrollpane = new JScrollPane(taskEntryTable);
		// create a window
		 //taskTablePanel = new javax.swing.JPanel();;
		taskTablePanel.setLayout(new BorderLayout());
		taskTablePanel.add(scrollpane, BorderLayout.CENTER);
		

}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

    	taskTablePanel  = new javax.swing.JPanel(); 
        queryPanel = new javax.swing.JPanel();
        leftSidePanel = new javax.swing.JPanel();
        queryProjectButton = new javax.swing.JButton();
        createTaskButton = new javax.swing.JButton();
        queryMemberButton = new javax.swing.JButton();
        createProjectButton = new javax.swing.JButton();
        editProjectButton = new javax.swing.JButton();
        editUserButton = new javax.swing.JButton();
        createUserButton = new javax.swing.JButton();
        query1Panel = new javax.swing.JPanel();
        queryProjectPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        queryProjectTable = new javax.swing.JTable();
        queryprojectSubmitButton = new javax.swing.JButton();
        queryProjectClearButton = new javax.swing.JButton();
        projectNametextField = new javax.swing.JTextField();
        projectNameTextField = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        membertable = new javax.swing.JTable();
        queryTeamPanel = new javax.swing.JPanel();
        memberNameLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taskTable = new javax.swing.JTable();
        queryTeamSubmitButton = new javax.swing.JButton();
        queryTeamClearButton = new javax.swing.JButton();
        memberNameTextField = new javax.swing.JTextField();
        createTaskPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        taskEntryTable = new javax.swing.JTable();
        taskNameLabel = new javax.swing.JLabel();
        taskDescriptionLabel = new javax.swing.JLabel();
        projectedCostLabel = new javax.swing.JLabel();
        actualCostLabel = new javax.swing.JLabel();
        dependencyLabel = new javax.swing.JLabel();
        startDateLabel = new javax.swing.JLabel();
        endDateLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        taskNameTextField = new javax.swing.JTextField();
        taskDescriptionTextField = new javax.swing.JTextField();
        projectedCostTextField = new javax.swing.JTextField();
        actualCostTextFeild = new javax.swing.JTextField();
        dependencyTextField = new javax.swing.JTextField();
        startDateTextField = new javax.swing.JTextField();
        endDateTextField = new javax.swing.JTextField();
        statusTextField = new javax.swing.JTextField();
        createTaskAddButton = new javax.swing.JButton();
        createTaskDeleteButton = new javax.swing.JButton();
        createTaskEditUpdateButton = new javax.swing.JButton();
        createTaskClearButton = new javax.swing.JButton();
        userNameLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        projName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        projStatus = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        projPartner = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        projStoreName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        projDesc = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        projProjectedCost = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        projActualCost = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        projOutcome = new javax.swing.JTextField();
        projStDay = new javax.swing.JFormattedTextField();
        projStMonth = new javax.swing.JFormattedTextField();
        projStYear = new javax.swing.JFormattedTextField();
        projEndDay = new javax.swing.JFormattedTextField();
        projEndMon = new javax.swing.JFormattedTextField();
        projEndYear = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        projDiscDay = new javax.swing.JFormattedTextField();
        projDiscMon = new javax.swing.JFormattedTextField();
        projDiscYear = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        projDesc1 = new javax.swing.JTextArea();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        queryPanel.setBackground(new java.awt.Color(255, 255, 255));

        leftSidePanel.setBackground(new java.awt.Color(255, 255, 255));

        queryProjectButton.setText("Qyery Project");
        queryProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryProjectButtonActionPerformed(evt);
            }
        });

        createTaskButton.setText("Ceate/Edit Task");
        createTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTaskButtonActionPerformed(evt);
            }
        });

        queryMemberButton.setText("Query Member");
        queryMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryMemberButtonActionPerformed(evt);
            }
        });

        createProjectButton.setText("Create Project");
        createProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	createProjectButtonActionPerformed(evt);
            }
        });
        editProjectButton.setText("Edit project");

        editUserButton.setText("Edit User");

        createUserButton.setText("Create User");

        javax.swing.GroupLayout leftSidePanelLayout = new javax.swing.GroupLayout(leftSidePanel);
        leftSidePanel.setLayout(leftSidePanelLayout);
        leftSidePanelLayout.setHorizontalGroup(
            leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftSidePanelLayout.createSequentialGroup()
                .addGroup(leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(queryMemberButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(queryProjectButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createTaskButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createProjectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editProjectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        leftSidePanelLayout.setVerticalGroup(
            leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSidePanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(createUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createProjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editProjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(queryProjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(queryMemberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        query1Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        query1Panel.setLayout(new java.awt.CardLayout());
        
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Project Name");
        jLabel1.setPreferredSize(new java.awt.Dimension(74, 14));

        jLabel2.setText("Project Status");

        jLabel3.setText("Partner Name ");

        projPartner.setToolTipText("");

        jLabel4.setText("Store Name ");

        jLabel5.setText("Date of Discussion");

        jLabel6.setText("Project Description");
        projDesc.setColumns(20);
        projDesc.setRows(5);
        jScrollPane1.setViewportView(projDesc);

        jLabel7.setText("Project Start Date");

        jLabel8.setText("Project End Date");

        jLabel9.setText("Project Projected Cost");

        projProjectedCost.setToolTipText("");
        
        jLabel10.setText("Project Actual Cost");

        projActualCost.setToolTipText("");

        jLabel11.setText("Project Expected Outcome");


        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

		projStDay.setColumns(2);
        projStDay.setToolTipText("Enter Date");

		projStMonth.setColumns(2);
        projStMonth.setToolTipText("Enter Month in format MM(Numbers 1-12)");

		projStYear.setColumns(4);
        projStYear.setToolTipText("Enter Year in format YYYY");

		projEndDay.setColumns(2);
        projEndDay.setToolTipText("Enter Date");

		projEndMon.setColumns(2);
        projEndMon.setToolTipText("Enter Month in format MM(Numbers 1-12)");

		projEndYear.setColumns(4);
        projEndYear.setToolTipText("Enter Year in format YYYY");
 

        jLabel12.setText("  Day");

        jLabel13.setText("Mon");

        jLabel14.setText("Year");

        jLabel15.setText("Day");

        jLabel16.setText("Mon");

        jLabel17.setText("Year");

		projDiscDay.setColumns(2);
        projDiscDay.setToolTipText("Enter Date");

		projDiscMon.setColumns(2);
        projDiscMon.setToolTipText("Enter Month in format MM(Numbers 1-12)");

		projDiscYear.setColumns(4);
        projDiscYear.setToolTipText("Enter Year in format YYYY");

        jLabel18.setText("  Day");

        jLabel19.setText("Mon");

        jLabel20.setText("Year");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(28, 28, 28)
                        .addComponent(jButton5)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(projName)
                                    .addComponent(projPartner))
                                .addGap(74, 74, 74)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(13, 13, 13))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(projOutcome)
                                            .addGap(96, 96, 96)))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(projProjectedCost, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addGap(4, 4, 4)
                                                        .addComponent(projStDay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(projStMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel13)))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel14)
                                                    .addComponent(projStYear, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(65, 65, 65)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel16))
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(projEndDay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(projEndMon, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(projStoreName, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(projActualCost, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(projStatus))
                                .addGap(156, 156, 156))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(projEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(projDiscDay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(projDiscMon, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20)
                                    .addComponent(projDiscYear, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projName)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(projStatus))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(projPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(projStoreName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projDiscDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projDiscMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projDiscYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(projStDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(projStMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(projStYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(projEndDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(projEndMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(projEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(projProjectedCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(projActualCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(projOutcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5)))
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        query1Panel.add(jPanel5, "card2");
        
        queryProjectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Project Desc", "Project Status"
            }
        ));
        jScrollPane1.setViewportView(queryProjectTable);

        queryprojectSubmitButton.setText("Submit");
        queryprojectSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	queryprojectSubmitButton(evt);
            }

			private void queryprojectSubmitButton(ActionEvent evt) {
				 String projectName = projectNametextField.getText();
			       displayQueryByProjectNameResult(ProjectService.getProjectByProjectName(projectName));
				
			}
        });

        queryProjectClearButton.setText("Clear");

        projectNameTextField.setText("Project Name");

        membertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Team Members"
            }
        ));
        jScrollPane3.setViewportView(membertable);

        javax.swing.GroupLayout queryProjectPanelLayout = new javax.swing.GroupLayout(queryProjectPanel);
        queryProjectPanel.setLayout(queryProjectPanelLayout);
        queryProjectPanelLayout.setHorizontalGroup(
            queryProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(queryProjectPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(queryProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(queryProjectPanelLayout.createSequentialGroup()
                        .addGroup(queryProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(queryProjectPanelLayout.createSequentialGroup()
                                .addComponent(projectNametextField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(queryprojectSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addComponent(queryProjectClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        queryProjectPanelLayout.setVerticalGroup(
            queryProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(queryProjectPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(queryProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectNametextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(queryprojectSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(queryProjectClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(676, Short.MAX_VALUE))
        );

        query1Panel.add(queryProjectPanel, "card2");

        memberNameLabel.setText("Member Name");

        taskTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Task Name", "Task Desc", "Start Date", "End Date", "Status"
            }
        ));
        jScrollPane2.setViewportView(taskTable);

        queryTeamSubmitButton.setText("Submit");
        queryTeamSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	queryteamSubmitButton(evt);
            }

			private void queryteamSubmitButton(ActionEvent evt) {
				// TODO Auto-generated method stub
				String memberName = memberNameTextField.getText();
		    	displayQueryTaskByMemberNameResult(UserService.getUserByUserName(memberName));
		    	
			}
        });

        queryTeamClearButton.setText("Clear");

        javax.swing.GroupLayout queryTeamPanelLayout = new javax.swing.GroupLayout(queryTeamPanel);
        queryTeamPanel.setLayout(queryTeamPanelLayout);
        queryTeamPanelLayout.setHorizontalGroup(
            queryTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(queryTeamPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(queryTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(queryTeamPanelLayout.createSequentialGroup()
                        .addComponent(memberNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(queryTeamSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(queryTeamClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        queryTeamPanelLayout.setVerticalGroup(
            queryTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(queryTeamPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(memberNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(queryTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(queryTeamSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(queryTeamClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(597, Short.MAX_VALUE))
        );

        query1Panel.add(queryTeamPanel, "card2");

        taskEntryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "User Name", "Task Name", "Task Desc", "Projected Cost", "Actual Cost", "Dependency", "Start Date", "End Date", "Status"
            }
        ));
        jScrollPane6.setViewportView(taskEntryTable);

        taskNameLabel.setText("Task Name");

        taskDescriptionLabel.setText("Task Description");

        projectedCostLabel.setText("Projected Cost");

        actualCostLabel.setText("Actual Cost");

        dependencyLabel.setText("Dependency");

        startDateLabel.setText("Start Date");

        endDateLabel.setText("End Date");

        statusLabel.setText("Status");

        createTaskAddButton.setText("Add");
        createTaskAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTaskAddButtonActionPerformed(evt);
            }
        });

        createTaskDeleteButton.setText("Delete");
        createTaskDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTaskDeleteButtonActionPerformed(evt);
            }
        });

        createTaskEditUpdateButton.setText("Edit/Update");
        createTaskEditUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTaskEditUpdateButtonActionPerformed(evt);
            }
        });

        createTaskClearButton.setText("Clear");
        createTaskClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTaskClearButtonActionPerformed(evt);
            }
        });

        userNameLabel.setText("User Name");
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(taskTablePanel);
        taskTablePanel.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Integer.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Integer.MAX_VALUE)
        );

        javax.swing.GroupLayout createTaskPanelLayout = new javax.swing.GroupLayout(createTaskPanel);
        createTaskPanel.setLayout(createTaskPanelLayout);
        createTaskPanelLayout.setHorizontalGroup(
            createTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createTaskPanelLayout.createSequentialGroup()
                .addGap(0, 67, Short.MAX_VALUE)
                .addGroup(createTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                		.addComponent(taskTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                    
                    .addGroup(createTaskPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(createTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(projectedCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dependencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(actualCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taskDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taskNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(createTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taskNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taskDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(projectedCostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(actualCostTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dependencyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(createTaskPanelLayout.createSequentialGroup()
                                .addComponent(createTaskDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(createTaskEditUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(createTaskClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(createTaskPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(createTaskAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        createTaskPanelLayout.setVerticalGroup(
            createTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createTaskPanelLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(createTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(createTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectedCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectedCostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(createTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualCostTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(createTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dependencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dependencyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(createTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(createTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createTaskAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createTaskDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createTaskEditUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createTaskClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                  .addComponent(taskTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
               
                .addGap(32, 32, 32))
        );

        query1Panel.add(createTaskPanel, "card2");

        javax.swing.GroupLayout queryPanelLayout = new javax.swing.GroupLayout(queryPanel);
        queryPanel.setLayout(queryPanelLayout);
        queryPanelLayout.setHorizontalGroup(
            queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(queryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(query1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        queryPanelLayout.setVerticalGroup(
            queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(query1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(queryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(queryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    protected void createProjectButtonActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
    	// TODO add your handling code here:
    	query1Panel.removeAll();
    	query1Panel.repaint();
    	query1Panel.revalidate();
        
    	query1Panel.add(jPanel5);
    	query1Panel.repaint();
    	query1Panel.revalidate();
	}


	private void queryMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        query1Panel.removeAll();
        query1Panel.repaint();
        query1Panel.removeAll();

        query1Panel.add(queryTeamPanel);
        query1Panel.repaint();
        query1Panel.revalidate();
    }                                                 

    private void createTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        query1Panel.removeAll();
        query1Panel.repaint();
        query1Panel.removeAll();

        query1Panel.add(createTaskPanel);
        query1Panel.repaint();
        query1Panel.revalidate();

    }                                                

    private void queryProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
        query1Panel.removeAll();
        query1Panel.repaint();
        query1Panel.removeAll();

        query1Panel.add(queryProjectPanel);
        query1Panel.repaint();
        query1Panel.revalidate();
    }                                                  

    private void createTaskAddButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    	String[] array = new String[taskEntryTable.getColumnCount()];
    	array[0] = userNameTextField.getText();
    	array[1] = taskNameTextField.getText();
    	array[2] = taskDescriptionTextField.getText();
    	array[3] = projectedCostTextField.getText();
    	array[4] = actualCostTextFeild.getText();
    	array[5] = dependencyTextField.getText();
    	array[6] = startDateTextField.getText();
    	array[7] = endDateTextField.getText();
    	array[8] = statusTextField.getText();
    	
    	
   	   taskTableController.addRow( array,projectName);
    	
    }                                                   

    private void createTaskDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
    	taskTableController.deleteRow( taskEntryTable.getSelectedRow());
    }                                                      

    private void createTaskEditUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        // TODO add your handling code here:
    	String[] array = new String[taskEntryTable.getColumnCount()];
    	array[0] = userNameTextField.getText();
    	array[1] = taskNameTextField.getText();
    	array[2] = taskDescriptionTextField.getText();
    	array[3] = projectedCostTextField.getText();
    	array[4] = actualCostTextFeild.getText();
    	array[5] = dependencyTextField.getText();
    	array[6] = startDateTextField.getText();
    	array[7] = endDateTextField.getText();
    	array[8] = statusTextField.getText();
    	taskTableController.updateRow(array, taskEntryTable.getSelectedRow());
    }                                                          

    private void createTaskClearButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    	String empty = "";
    	userNameTextField.setText(empty);
    	taskNameTextField.setText(empty);
    	 taskDescriptionTextField.setText(empty);
    	 projectedCostTextField.setText(empty);
    	 actualCostTextFeild.setText(empty);
    	 dependencyTextField.setText(empty);
    	startDateTextField.setText(empty);
    	endDateTextField.setText(empty);
    	statusTextField.setText(empty);
    }                                                     
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	 // TODO add your handling code here:
    	// TODO add your handling code here:
    	//SHRUTHI USING BELOW CODE FOR SUBMIT FUNCTIONALITY
    	String[] array = new String[11];
    	array[0] = projName.getText();//project name
    	array[1] = projStatus.getText();//project status
    	array[2] = projPartner.getText();//partner
    	array[3] = projStoreName.getText();//store
    	array[4] = projDiscDay.getText()+"/"+projDiscMon.getText()+"/"+projDiscYear.getText();//date of discussion
    	array[5] = projDesc.getText();//project desc
    	array[6] = projStDay.getText()+"/"+projStMonth.getText()+"/"+projStYear.getText();//proj start date
    	array[7] = projEndDay.getText()+"/"+projEndMon.getText()+"/"+projEndYear.getText();//proj end date
    	array[8] = projProjectedCost.getText();//proj projected cost
    	array[9] = projActualCost.getText();//proj actual cost
    	array[10] = projOutcome.getText();//proj outcome
    	projPlannerController.addRow(array);
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame5("project1",false).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel actualCostLabel;
    private javax.swing.JTextField actualCostTextFeild;
    private javax.swing.JButton createProjectButton;
    private javax.swing.JButton createTaskAddButton;
    private javax.swing.JButton createTaskButton;
    private javax.swing.JButton createTaskClearButton;
    private javax.swing.JButton createTaskDeleteButton;
    private javax.swing.JButton createTaskEditUpdateButton;
    private javax.swing.JPanel createTaskPanel;
    private javax.swing.JButton createUserButton;
    private javax.swing.JLabel dependencyLabel;
    private javax.swing.JTextField dependencyTextField;
    private javax.swing.JButton editProjectButton;
    private javax.swing.JButton editUserButton;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JTextField endDateTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel leftSidePanel;
    private javax.swing.JLabel memberNameLabel;
    private javax.swing.JTextField memberNameTextField;
    private javax.swing.JTable membertable;
    private javax.swing.JLabel projectNameTextField;
    private javax.swing.JTextField projectNametextField;
    private javax.swing.JLabel projectedCostLabel;
    private javax.swing.JTextField projectedCostTextField;
    private javax.swing.JPanel query1Panel;
    private javax.swing.JButton queryMemberButton;
    private javax.swing.JPanel queryPanel;
    private javax.swing.JButton queryProjectButton;
    private javax.swing.JButton queryProjectClearButton;
    private javax.swing.JPanel queryProjectPanel;
    private javax.swing.JTable queryProjectTable;
    private javax.swing.JButton queryTeamClearButton;
    private javax.swing.JPanel queryTeamPanel;
    private javax.swing.JButton queryTeamSubmitButton;
    private javax.swing.JButton queryprojectSubmitButton;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JTextField startDateTextField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField statusTextField;
    private javax.swing.JLabel taskDescriptionLabel;
    private javax.swing.JTextField taskDescriptionTextField;
    private javax.swing.JTable taskEntryTable;
    private javax.swing.JLabel taskNameLabel;
    private javax.swing.JTextField taskNameTextField;
    private javax.swing.JTable taskTable;
    private javax.swing.JPanel taskTablePanel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField projActualCost;
    private javax.swing.JTextArea projDesc;
    private javax.swing.JTextArea projDesc1;
    private javax.swing.JFormattedTextField projDiscDay;
    private javax.swing.JFormattedTextField projDiscMon;
    private javax.swing.JFormattedTextField projDiscYear;
    private javax.swing.JFormattedTextField projEndDay;
    private javax.swing.JFormattedTextField projEndMon;
    private javax.swing.JFormattedTextField projEndYear;
    private javax.swing.JTextField projName;
    private javax.swing.JTextField projPartner;
    private javax.swing.JTextField projProjectedCost;
    private javax.swing.JFormattedTextField projStDay;
    private javax.swing.JFormattedTextField projStMonth;
    private javax.swing.JFormattedTextField projStYear;
    private javax.swing.JTextField projStatus;
    private javax.swing.JTextField projStoreName;
    private javax.swing.JTextField projOutcome;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    
   	public void setUserNameTextField(String valueAt) {
   		// TODO Auto-generated method stub
   		userNameTextField.setText(valueAt);
   		}

   	public void setTaskNameTextField(String valueAt) {
   		// TODO Auto-generated method stub
   		taskNameTextField.setText(valueAt);
   		}

   	public void setTaskDescriptionTextField(String valueAt) {
   		// TODO Auto-generated method stub
   		taskDescriptionTextField.setText(valueAt);
   		}

   	public void setProjectedCostTextField(String valueAt) {
   		// TODO Auto-generated method stub
   		projectedCostTextField.setText(valueAt);
   		}

   	public void setActualCostTextField(String valueAt) {
   		// TODO Auto-generated method stub
   		actualCostTextFeild.setText(valueAt);
   	}

   	public void setDependencyTextField(String valueAt) {
   		// TODO Auto-generated method stub
   		dependencyTextField.setText(valueAt);
   	}

   	public void setStartDateTextField(String valueAt) {
   		// TODO Auto-generated method stub
   		startDateTextField.setText(valueAt);
   	}

   	public void setEndDateTextField(String valueAt) {
   		// TODO Auto-generated method stub
   		endDateTextField.setText(valueAt);
   	}

   	public void setStatusTextField(String valueAt) {
   		// TODO Auto-generated method stub
   		statusTextField.setText(valueAt);
   	}

   	public void updateTable() {
   		// TODO Auto-generated method stub
   		taskEntryTable.setModel(taskTableController.getTableModel());
   	}

    
    // End of variables declaration      
    
    private void displayQueryTaskByMemberNameResult(User user) {
		// TODO Auto-generated method stub
		Vector<String> taskTableHeaders = new Vector<String>();
		Vector taskTableData = new Vector();
		taskTableHeaders.add("Task Name");
		taskTableHeaders.add("Task Description");
		taskTableHeaders.add("Start Date");
		taskTableHeaders.add("End Date");
		taskTableHeaders.add("Task Status");
		if( user != null){
			Set<Task> tasks = user.getTasks();
			for(Task task : tasks){
				Vector<Object> row = new Vector<Object>();
				row.add(task.getTaskName());
				row.add(task.getTaskDesc());
				row.add(task.getTaskStartDate());
				row.add(task.getTaskEndDate());
				row.add(task.getTaskStatus());
				taskTableData.add(row);
			}
		}
		
    taskTable.setModel(new DefaultTableModel(taskTableData,taskTableHeaders));
		
	}
    
    private void displayQueryByProjectNameResult(List resultList) {
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("Project Name");
        tableHeaders.add("Project Status");
        
        Vector<String> memberTableHeaders = new Vector<String>();
        Vector memberTableData = new Vector();
        memberTableHeaders.add("Member Name");
        if(resultList!= null && resultList.size() > 0) {
        	Project project = (Project) resultList.get(0);
            Vector<Object> oneRow = new Vector<Object>();
            oneRow.add(project.getProjName());
            oneRow.add(project.getProjStatus());
            tableData.add(oneRow);
            if(project.getTeam() != null ){
            	Set<TeamMember>teamMemberSet = project.getTeam().getTeamMembers();
            	for(TeamMember teamMember : teamMemberSet){
            		 Vector<Object> row = new Vector<Object>();
            		 //User  user = UserService.getUserById(teamMember.getUser().);
            		 row.add(teamMember.getUser().getUserName());
            		 memberTableData.add(row);
            	
            }
        }
       
        queryProjectTable.setModel(new DefaultTableModel(tableData, tableHeaders));
        membertable.setModel(new DefaultTableModel(memberTableData,memberTableHeaders));
        

    }
    }

}
